services:
  - type: web
    name: agriassist
    runtime: python

    plan: free

    healthCheckPath: /_stcore/health

    buildCommand: |
      pip install --upgrade pip
      pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
      bash render_setup.sh

    startCommand: streamlit run app/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --server.enableWebsocketCompression=false

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: GEMINI_API_KEY
        sync: false
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: HF_HUB_DISABLE_TELEMETRY
        value: "1"