services:
  - type: web
    name: agriassist
    runtime: python

    plan: free

    healthCheckPath: /_stcore/health

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: streamlit run app/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --server.enableWebsocketCompression=false

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: GEMINI_API_KEY
        sync: false